[build]
  command = "npm run build"
  publish = "dist"

# The Redirect Magic
[[redirects]]
  from = "/api/movies"
  to = "/.netlify/functions/movie"
  status = 200

  [functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"